<?php
/**
 * Created by PhpStorm.
 * User: Call
 * Date: 18/08/2016
 * Time: 10:33
 */

namespace Admin\Form;


use Base\Form\AbstractForm;
use Interop\Container\ContainerInterface;

class ConfiguracaoForm extends AbstractForm {
    public function __construct(ContainerInterface $containerInterface, $name = null, $options = [])
    {
        parent::__construct($containerInterface, $name, $options); // TODO: Change the autogenerated stub
        $this->setInputFilter($containerInterface->get(ConfiguracaoFilter::class));
        $this->setId([]);
        $this->setAssetid([]);
        $this->setCodigo([]);
        $this->setEmpresa([]);
        $this->setAtachament([]);
        $this->setCaptha([]);
        $this->setDescription([]);
        $this->setAccess([]);
        $this->setState([]);
        $this->setCsrf([]);

    }


} 