<?php
/**
 * Created by PhpStorm.
 * User: Call
 * Date: 17/08/2016
 * Time: 10:21
 */

namespace Base\Form;


use Interop\Container\ContainerInterface;
use Zend\Form\Form;

class AbstractForm extends Form {
    /**
     * @var ContainerInterface
     */
    protected  $containerInterface;

    /**
     * @param ContainerInterface $containerInterface
     * @param null $name
     * @param array $options
     */
    public function __construct(ContainerInterface $containerInterface,$name = null, $options = [])
    {
        parent::__construct($name, $options); // TODO: Change the autogenerated stub
        $this->containerInterface = $containerInterface;
        $this->setAttribute('class','form-horizontal');

    }


    /**
     * @param $element
     */
    public function addElements($element=[])
    {
        $input=array_replace([
                'type' => 'text',
                'name' => 'name',
                'options' => [
                    'label' => 'FILD_LABEL_LABEL',
                ],
                'attributes' =>array_filter([
                    'id' => 'id',
                    'title' => '',
                    'class' => 'form-control',
                    'data-access' => '3',
                    'data-position' => 'geral',
                ]),
            ]
            ,$element);
        $this->add(array_filter($input));

    }


    /**
     * @param $id
     */
    public function setId($id=[])
    {
        $this->add(array_replace([
            'type'=>'hidden',
            'name'=>'id',
            'options'=>[],
            'attributes'=>[
                'id'=>'id',
                'value'=>'AUTOMATICO',
                'data-position' => 'geral',
            ]
        ], $id));
    }

    /**
     * @param array $empresa
     */
    public function setEmpresa($empresa=[])
    {
        $this->add(array_replace([
            'type'=>'hidden',
            'name'=>'empresa',
            'options'=>[],
            'attributes'=>[
                'id'=>'empresa',
                'value' => '',
                'data-access' => '3',
                'data-position' => 'geral',
            ]
        ],$empresa));
    }

    /**
     * @param array $codigo
     */
    public function setCodigo($codigo=[])
    {
        $this->add(array_replace([
            'type'=>'hidden',
            'name'=>'codigo',
            'options'=>[],
            'attributes'=>[
                'id'=>'codigo',
                'value'=>'8',
                'data-position' => 'geral'
            ]
        ],$codigo));
    }

    /**
     * @param array $assetid
     */
    public function setAssetid($assetid=[])
    {
        $this->add(array_replace([
            'type'=>'hidden',
            'name'=>'asset_id',
            'options'=>[],
            'attributes'=>[
                'id'=>'asset_id',
                'id' => 'asset_id',
                'value' =>'1',//isset($this->authservice['empresa'])? md5($this->authservice['empresa']):'1',
                'data-access' => '3',
                'data-position' => 'geral',
            ]
        ],$assetid));
    }

    /**
     * @param mixed $description
     */
    public function setDescription($description=[])
    {
        $this->add(array_replace([
                'type' => 'textarea',
                'name' => 'description',
                'options' => [
                    'label' => 'FILD_DESCRIPTION_LABEL',
                ],
                'attributes' => [
                    'id' => 'description',
                    'title' => 'FILD_DESCRIPTION_DESC',
                    'class' => 'form-control',
                    'placeholder' => 'FILD_DESCRIPTION_PLACEHOLDER',
                    'rows' => '5',
                    'cols' => '20',
                    'data-access' => '3',
                    'data-position' => 'geral',
                ],
            ]
            ,$description));
    }



    /**
     * @param array $access
     */
    public function setAccess($access=[])
    {
        $this->add(array_replace([
            'type'=>'select',
            'name'=>'access',
            'options'=>[
                'label' => 'FILD_ACCESS_LABEL',
                "disable_inarray_validator" => true,
            ],
            'attributes'=>[
                'id' => 'access',
                'title' => 'FILD_ACCESS_DESC',
                'class' => 'form-control',
                'placeholder' => 'FILD_ACCESS_PLACEHOLDER',
                'data-access' => '3',
                'value'=>'3',
                'data-position' => 'datas',
            ]
        ],$access));
    }

    /**
     * @param mixed $state
     */
    public function setState($state=[])
    {
        $this->add(array_replace([
            'type'=>'select',
            'name'=>'state',
            'options'=>[
                'label' => 'FILD_STATE_LABEL',
                "disable_inarray_validator" => true,
            ],
            'attributes'=>[
                'id' => 'state',
                'title' => 'FILD_STATE_DESC',
                'class' => 'form-control',
                'placeholder' => 'FILD_STATE_PLACEHOLDER',
                'data-access' => '3',
                'data-position' => 'datas',
            ]
        ],$state));
    }
    /**
     * @param array $created
     */
    public function setCreated($created=[])
    {
        $this->add(array_replace([
            'type'=>'text',
            'name'=>'created',
            'options'=>['label' => 'FILD_CREATED_LABEL'],
            'attributes'=>[
                'id' => 'created',
                'title' => 'FILD_CREATED_DESC',
                'class' => 'form-control',
                'placeholder' => 'FILD_CREATED_PLACEHOLDER',
                'readonly' => true,
                'data-access' => '3',
                'data-position' => 'datas',
            ]
        ],$created));
    }



    /**
     * @param array $modified
     */
    public function setModified($modified=[])
    {
        $this->add(array_replace([
            'type'=>'text',
            'name'=>'modified',
            'options'=>['label' => 'FILD_MODIFIED_LABEL'],
            'attributes'=>[
                'id'=>'modified',
                'title' => 'FILD_MODIFIED_DESC',
                'class' => 'form-control',
                'placeholder' => 'FILD_MODIFIED_PLACEHOLDER',
                'value'=>date("d-m-Y"),
                'data-access' => '3',
                'data-position' => 'datas',
            ]
        ],$modified));
    }


    /**
     * @param mixed $csrf
     */
    public function setCsrf($csrf)
    {
        $this->add(array_replace([
            'type' => 'Zend\Form\Element\Csrf',
            'name' => 'security',
            'options' => [
                'csrf_options' =>[
                    'timeout' => 600
                ]
            ], 'attributes' => [
                'data-access' => '3',
                'data-position' => 'geral',
            ]
        ],$csrf));
    }


    /**
     * @param mixed $atachament
     */
    public function setAtachament($atachament)
    {
        $this->add(array_replace([
                'type' => 'file',
                'name' => 'atachament',
                'options' => [
                    'label' => 'FILD_ATACHAMENT_LABEL',
                ],
                'attributes' => [
                    'id' => 'atachament',
                    'title' => 'FILD_ATACHAMENT_DESC',
                    'class' => 'atachament',
                    'data-access' => '3',
                    'data-position' => 'geral',
                ],
            ]
            ,$atachament));
    }

    /**
     * @param $captha
     */
    public function setCaptha($captha){

        $this->add(array_replace([
                'type' => 'Zend\Form\Element\Captcha',
                'name' => 'captcha',
                'options' => [
                    'label' => 'Please verify you are human.',
                    'captcha' => [
                        'class'   => 'Image',
                        'options' => [
                            'font' =>  './data/arial.ttf',
                            'width' => 200,
                            'height' => 100,
                            'dotNoiseLevel' => 40,
                            'lineNoiseLevel' => 3,
                            'wordLen' => 3,
                            'imgDir' => './public/images/captcha/generated',
                            'imgUrl' => '/images/captcha/generated'
                        ],
                    ],
                ],
                'attributes' => [
                    'id' => 'captcha',
                    'title' => 'FILD_CAPTHA_DESC',
                    'class' => 'form-control',
                    'data-access' => '3',
                    'data-position' => 'geral',
                ]
            ]
            ,$captha));
    }


} 